### ISSUE TITLE
uncastmycode command

### ISSUE THREAD

**Issue by zulhfreelancer** [zulfajuniadi/castmycode-agent#1]
Salam bro,

Dekat page https://castmycode.com/usage on step #4 tu kan, kena hit `control + c` dulu kan sebelum command `uncastmycode`?

Maybe kena letak juga tu dekat dalam page usage ni. Sebab tadi saya terus guna command `uncastmycode` dekat dalam terminal, nothing happened.

Lepas hit `control + c` baru jadi guna command `uncastmycode`.

**Comment by zulfajuniadi** [comment]
Done
