### ISSUE TITLE
100 file limit is not enough

### ISSUE THREAD

**Issue by kamudrikah** [zulfajuniadi/castmycode-agent#3]
I want to share with my buddies on how to use CodeIgniter. Clearly would like to use CastMyCode but cant because of the 100 file limit. CodeIgniter framework alone is more than 100. So.. yeah..

**Comment by zulfajuniadi** [comment]
You can use .ccignore file to ignore all files not related to your
presentation for example libraries that does not change.

On Thursday, 19 May 2016, Ku Ahmad Mudrikah notifications@github.com
wrote:

> I want to share with my buddies on how to use CodeIgniter. Clearly would
> like to use CastMyCode but cant because of the 100 file limit. CodeIgniter
> framework alone is more than 100. So.. yeah..
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/zulfajuniadi/castmycode-agent/issues/3

## 

---

Zulfa Juniadi bin Zulkifli
HP: +60 19 2727 155
